name: Build and Deploy

on:
  push:
    branches:
    - main
    paths:
    - book/**
    - requirements.txt
    - .github/workflows/deploy.yml
  workflow_dispatch:

jobs:
  call-workflow:
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
